### ISSUE TITLE
Modificar BD, agregar tabla para tickets pagados pagos y detalle_pagos por concepto 1-N

### ISSUE THREAD

**Issue by versusdiaz** [transmarim/sigtsm#1]
Modificar BD, agregar tabla para tickets pagados pagos y detalle_pagos por concepto 1-N

**Comment by thewardex** [comment]
falta agregar tabla de chat

**Comment by versusdiaz** [comment]
Toma descarga el workbench pa tu pc intenta x aqui hay de 32bit
https://downloads.mysql.com/archives/workbench/

**Comment by versusdiaz** [comment]
Tabla de chat agregada

**Comment by versusdiaz** [comment]
Este modulo se piensa descartar, por favor confirmar, se sustituye por un cierre semanal del sistema

**Comment by versusdiaz** [comment]
Cierre del sistema creado en 01dfef31b496f555ad210b5047cdcf1159424ee2
