### ISSUE TITLE
Agregar tabla de tarifas de choferes, viajes y horas extras.

### ISSUE THREAD

**Issue by thewardex** [transmarim/sigtsm#10]
las horas extras varían según el lugar a donde sea el traslado. Esto se toma en cuenta mas que todo con los chóferes que viajan. La espera fuera del estado es un poco mas que la que normalmente se cobra aquí.

**Comment by versusdiaz** [comment]
Ya la tabla de tarifas esta creada en BD tiene todas las entidades que mencionas listas, revisa comenta y dale cierre al issue si todo esta bien.

Ojo: Se va manejar 1 sola tabla llamada tarifas (esta incluye todas, choferes,viajes,tsm,carribean) no es necesario crear tablas independient
