### ISSUE TITLE
Tabla de chóferes fuera de servicio

### ISSUE THREAD

**Issue by thewardex** [transmarim/sigtsm#12]
No esta elaborada, pero si lo toman en cuenta, saben que ese chófer esta fuera, hasta que se reintegre. También debo hacer un borrador en una hoja para tener una idea.

**Comment by versusdiaz** [comment]
Pienso que se debe crear una tabla que se llame pizarra, si te fijas esto no tiene mucha relevancia en el sistema esto aplica con todos los demas issue que creaste

**Comment by versusdiaz** [comment]
Se pretende cambiar la pizarra por el muro o chat

**Comment by versusdiaz** [comment]
Modulo chat creado
