### ISSUE TITLE
Documentos de choferes(requisitos)

### ISSUE THREAD

**Issue by thewardex** [transmarim/sigtsm#15]
- Certificado de registro de vehículo.
- Autorización de manejo y porte = Cuando el vehículo es prestado.
- Cédula.
- Certificado de circulación.
- Licencia para conducir.
- Examen medico.
- Certificado medico de salud integral para conducir vehículos a motor.
- Seguro del vehículo = Cuadro de póliza.
- Registro de vehículo.
- Declaración jurada de origen y destino licito de fondos.

**Comment by versusdiaz** [comment]
De los que mencionas tenemos en el sistema:

- Certificado de registro de vehículo.
- Cédula.
- Certificado de circulación.
- Licencia para conducir.
- Seguro del vehículo = Cuadro de póliza.
- Registro de vehículo = El titulo? si es asi si.

Queda pendiente: 

- Examen medico.
- Certificado de circulación.
- Declaración jurada de origen y destino licito de fondos.

Tienes que abstraer la idea y darle forma.

**Comment by thewardex** [comment]
El registro del vehículo se refiere a cuando el carro fue de una persona y lo compro otra. en este caso el vehículo del cual se habla es de una persona que se le compro a otra.

-No estoy del todo claro pero creo que vendría siendo lo mismo que el titulo del vehiculo.

**Comment by versusdiaz** [comment]
Ese es el traspaso del vehiculo, un documento compra-venta, pero igual necesitas tener el titulo el carro en el sistema, sin importar quien sea el dueno

**Comment by versusdiaz** [comment]
Tema aclarado
