### ISSUE TITLE
Error pantalla al registrar y modificar usuario, relacionados con el permiso.

### ISSUE THREAD

**Issue by thewardex** [transmarim/sigtsm#18]
Puede ser por que al registrar un nuevo usuario no se define que tipo de permiso va a poseer su cuenta.

**Comment by versusdiaz** [comment]
Se debe hacer una validación para ver si por lo menos 1 checkbox esta seleccionado

**Comment by thewardex** [comment]
Este error ya esta solucionado, no?

**Comment by versusdiaz** [comment]
Si y no, esta identificado pero aun no se agregan la validaciones, deberiamos dejarlo indicado y al final cargar un parche o version con todos campos validados, ya que es trabajoso

**Comment by versusdiaz** [comment]
Error solucionado, agregando validacion de 1 checkbox como minimo, incluso si es un chofer se le debe dar 1 permiso.
4882f16794656dca99eee1eb215e61ba1a5e1b6a
