### ISSUE TITLE
Modulo de control de vehiculos

### ISSUE THREAD

**Issue by thewardex** [transmarim/sigtsm#4]
En el campo de modelo: se debe especificar nombre del modelo y año. Se debería hacer un campo solo para especificar el año ?

El tamaño de la imagen que requiere en este modulo debe ser mas px para poder adjuntar el archivo completo de la imagen del titulo.

**Comment by versusdiaz** [comment]
1 - Si hay que crear un campo adicional solo para especificar el año.

2- Para el titulo no he pensado usar px, ya que estaba viendo y creo que es mejor manejarlo con un archivo PDF.

**Comment by versusdiaz** [comment]
Asunto resuelto cierro el issue
