### ISSUE TITLE
Control de usuarios

### ISSUE THREAD

**Issue by thewardex** [transmarim/sigtsm#5]
Peqe pienso que el nombre como requisito en este modulo esta demás, no se si me equivoco, pero si te va a pedir que vincules esos datos con los de algún chófer que se supone debe estar ya registrado, ya este debería estar registrado con el mismo nombre que pide este campo. No se si me equivoco o estoy analizando mal la broma.

**Comment by versusdiaz** [comment]
Estas analizando mal, recuerda que el modulo de usuarios no solo son los choferes.. ya que ellos tienen su propio modulo.
El modulo de usuario debe servir tambien para los usuarios administrativos. (Estos no son choferes).

**Comment by versusdiaz** [comment]
Discutido y aclarado cierro issue
