### ISSUE TITLE
Descuentos

### ISSUE THREAD

**Issue by thewardex** [transmarim/sigtsm#7]
1.  ISLR
2.  Falta de sello en la boleta
3.  Tickets clonados
4.  Falta de la firma del nombre o firma del cliente.
5.  250 bs cuando supera el monto de 25000 bsf (solo aplica transmarine)

**Comment by thewardex** [comment]
También se debe agregar el **descuento del banco** cuando se hacen **transferencias**.

**Comment by versusdiaz** [comment]
Trata de ubicar los montos bs de los descuentos

**Comment by versusdiaz** [comment]
Issue cerrado, con la aplicacion de descuentos se integran al momento de emitir el pronto pago
