### ISSUE TITLE
CORREOS DE EMPRESAS

### ISSUE THREAD

**Issue by thewardex** [transmarim/sigtsm#9]
Algunas boletas necesitan de confirmación de haber realizado dicho servicio, aquí es donde el supervisor de operaciones se encarga de buscar el correo de la respectiva empresa y escribirle para que de constancia y confirme de que si se llevo a cabo el servicio. (No tengo claro aun cuales son las empresas a las que solicitan esa confirmación)

**Comment by versusdiaz** [comment]
Eso se hace desde Gmail, no entra como un modulo, de igual manera, usas el campo email de la tabla clientes, si necesita tener el correo que vaya a los datos de la empresa o cliente registrado.
